config/routes.rb
Rails.application.routes.draw do

  root to: 'user_sessions#new'

  get  'recipes'       => 'recipe#index',  :as => 'recipes_list'
  get  'recipe'        => 'recipe#new',    :as => 'new_recipe'
  post 'recipe/create' => 'recipe#create', :as => 'create_recipe'
  get  'recipe/:id'    => 'recipe#show',   :as => 'view_recipe'

  get 'ingredients/autocomplete_ingredient_name'

  get 'login'  => 'user_sessions#new',     :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  resources :user_sessions, only: [:create]

  get 'user/new'      => 'users#new',    :as => 'new_user'
  get 'user'          => 'users#edit',   :as => 'user'
  patch 'users/edit'  => 'users#update', :as => 'update_user'
  post 'users/create' => 'users#create', :as => 'create_user'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates_uniqueness_of :name

  def self.find_or_create(name:)
    Ingredient.where(:name => name).first || Ingredient.create!(:name => name)
  end
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_ingredients

  validates :name, :servings, :prep_time_in_minutes, :presence => true

  def add_ingredient(ingredient)
    self.recipe_ingredients << RecipeIngredient.new(:ingredient => ingredient)
  end

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  has_one    :measurement
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic do |c|
    c.login_field            = :email
    c.crypted_password_field = :encrypted_password
    c.crypto_provider        = Authlogic::CryptoProviders::BCrypt
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.record
  end

  def require_user
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to login_path
      return false
    end
  end

  def store_location
    session[:return_to] = request.path
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  autocomplete :ingredient, :name
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  before_action :require_user

  def index
    @heading = "Recipes List"
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    form = Recipe::Form.new(recipe_params)
    use_case = Recipe::Create.new(form)
    use_case.perform

    if use_case.success?
      redirect_to view_recipe_path(use_case.recipe_id)
    else
      render 'new'
    end
  end

  def show
    @recipe = Recipe.find(recipe_id)
    @heading = @recipe.name
  end

private

  def recipe_id
    @recipe_id ||= params[:id].to_i
  end

  def recipe_params
    params.slice(:name, :prep_time_in_minutes, :servings, :ingredient)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_user, only: [:destroy]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])

    if @user_session.save
      flash[:notice] = "You have successfully logged in."
      redirect_to recipes_list_url
    else
      render :action => 'new'
    end
  end

  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = "You have successfully logged out."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      flash[:notice] = "Your account has been registered"
      redirect_to root_url
    else
      render :action => :new
    end
  end

  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end

  def update
    @user = @current_user
    if @user.update_attributes(user_params)
      flash[:notice] = "Your account has been updated"
      redirect_to root_url
    else
      render :action => :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
  <div id="flash_notice"><%= flash[:notice] %></div>
<% elsif flash[:error] %>
  <div id="flash_error"><%= flash[:error] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @heading || 'Recipes' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'shared/flash_messages', flash: flash %>

<div id="user_nav">
  <% if current_user %>
    <%= link_to "My Account", user_path %> |
    <%= link_to "Logout", logout_path %>
  <% else %>
    <%= link_to "Register", new_user_path %> |
    <%= link_to "Login", login_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/recipe/_form.html.erb
<%= form_tag create_recipe_path do |form| %>
  <p>
    <b><%= label_tag :name %></b>
    <%= text_field_tag :name %>
  </p>
  <p>
    <b><%= label_tag :prep_time_in_minutes %></b>
    <%= number_field_tag :prep_time_in_minutes %>
  </p>
  <p>
    <b><%= label_tag :servings %></b>
    <%= number_field_tag :servings %>
  </p>
  <p>
    <b><%= label_tag :ingredient %></b>
    <%= autocomplete_field_tag :ingredient, params[:ingredient], ingredients_autocomplete_ingredient_name_path, {class: "search-query", placeholder: "Ingredients", type: "search"} %><br>
  </p>

  <%= submit_tag("Create") %>
<% end %>

app/views/recipe/_recipe_details.html.erb
<b>Prep Time:</b> <%= @recipe.prep_time_in_minutes %><br>
<b>Servings:</b> <%= @recipe.servings %><br>

app/views/recipe/index.html.erb
<h1>Recipes</h1>

<% @recipes.each do |recipe| %>
  <%= link_to recipe.name, view_recipe_path(recipe.id) %><br>
<% end %>

<p>
<%= link_to 'Add New Recipe', new_recipe_path %>
</p>

app/views/recipe/new.html.erb
<h1>Add a Recipe</h1>

<%= render 'form' %>

app/views/recipe/show.html.erb
<h1><%= @recipe.name %></h1>
<b>Prep Time:</b> <%= @recipe.prep_time_in_minutes %><br>
<b>Servings:</b> <%= @recipe.servings %><br>
<b>Ingredients:</b><br>
<% @recipe.ingredients.each do |ingredient| %>
<%= ingredient.name %><br>
<% end %>


<p><%= link_to "View all Recipes", recipes_list_path %></p>

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] %>
  <div id="flash_notice"><%= flash[:notice] %></div>
<% elsif flash[:error] %>
  <div id="flash_error"><%= flash[:error] %></div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for @user_session do |f| %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit "Log in" %></p>
<% end %>

app/views/users/edit.html.erb
<h3>Edit Account</h3>

<%= form_for @user, url: update_user_path do |f| %>
  <p>
    <b><%= f.label :username %></b>  <%= f.text_field :username %>
  </p>
  <p>
    <b><%= f.label :email %></b> <%= f.text_field :email %>
  </p>
  <p>
    <b><%= f.label :password %></b> <%= f.password_field :password %>
  </p>
  <p>
    <b><%= f.label :password_confirmation %></b> <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h3>New Account</h3>

<%= form_for @user, url: create_user_path do |f| %>
  <p>
    <b><%= f.label :username %></b>  <%= f.text_field :username %>
  </p>
  <p>
    <b><%= f.label :email %></b> <%= f.text_field :email %>
  </p>
  <p>
    <b><%= f.label :password %></b> <%= f.password_field :password %>
  </p>
  <p>
    <b><%= f.label :password_confirmation %></b> <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit %>
<% end %>